name: dart_get_up_speed
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.7.0
dev_dependencies:
  lint: ^1.5.3
  freezed: ^0.14.2
  build_runner: ^2.0.4

dependencies:
  meta: ^1.3.0
  freezed_annotation: ^0.14.2
  http: ^0.13.3
